Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

EulerNet_default: # This is a config template
    model: EulerNet
    dataset_id: twitter_data_test10 # tencent_train
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC', 'ACC']
    task: binary_classification
    optimizer: adam
    shape: [20]
    net_ex_dropout: 0.0
    net_im_dropout: 0.0
    layer_norm: true
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 8192
    embedding_dim: 10
    epochs: 100
    shuffle: True
    seed: 2021
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
