Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

AutoInt_test:
    model: AutoInt
    dataset_id: tiny_npz
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-8
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 4
    dnn_hidden_units: [64, 32]
    dnn_activations: relu
    net_dropout: 0
    num_heads: 2
    attention_layers: 3
    attention_dim: 8
    use_residual: True
    batch_norm: False
    layer_norm: False
    use_scale: False
    use_wide: False
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

AutoInt_default:
    model: AutoInt
    dataset_id: twitter_data_test
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC', 'ACC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 8196 # 10000 # 8192是twitter数据集的结果, 10000是zhandi和shamo的训练，因为他们两的特征没那么多
    embedding_dim: 16
    dnn_hidden_units: [400, 400]
    dnn_activations: relu
    net_dropout: 0
    num_heads: 1
    attention_layers: 3
    attention_dim: 16
    use_residual: False
    batch_norm: True
    layer_norm: True
    use_scale: True
    use_wide: True
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
